In [ ]:
from huggingface_hub import list_datasets

print([dataset.id for dataset in list_datasets()])

In [10]:
import os, sys
os.environ["HF_HOME"] = 'cache/datasets/'
from datasets import *

module_path = r'C:\Users\el1ja\OneDrive\Рабочий стол\программирование\AI\NLP'
sys.path.append(module_path)

from nlp_utils.pandas_tools import *

import pandas as pd

In [57]:
# pd.set_option('display.max_rows', 500)
# pd.set_option('display.max_columns', 500)
# pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 300)

### LIBRA

https://huggingface.co/datasets/ai-forever/LIBRA

In [ ]:
def load_n_test_sample_of_each_dataset_name(dataset_name, count):
    datasets = {}
    for name in get_dataset_config_names(dataset_name):
        datasets[name] = load_dataset(dataset_name, name=name, split=f'test[:{count}]')
    return datasets

In [32]:
LIBRA = "ai-forever/LIBRA"

In [ ]:
datasets = load_n_test_sample_of_each_dataset_name(LIBRA, 3)

In [44]:
datasets['librusec_history']

Dataset({
    features: ['length', 'context', 'input', 'positive_outputs', 'negative_outputs', 'metadata'],
    num_rows: 3
})

In [49]:
datasets['librusec_history'].info.splits

{'test': SplitInfo(name='test', num_bytes=9288308, num_examples=128, shard_lengths=None, dataset_name='libra')}

In [34]:
datasets_df = {}

for name, dataset in datasets.items():
    datasets_df[name] = pd.DataFrame.from_dict(dataset)

In [40]:
datasets_df['librusec_history']

,length,context,input,positive_outputs,negative_outputs,metadata
0,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Пе...","Как называется роман, который перевёл Василий Кириллыч Тредиаковский?",[Езда на остров любви],[],"{'id': '665d8b09-e43b-4d8f-a5f9-ec2723d59037', 'source_path': 'librusec/01/shard_0102.txt'}"
1,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Пе...",Как при рождении назвали будущего императора Петра III?,[Карл Ульрих],[],"{'id': '8627ec4d-ecd5-4bf7-b1e2-d128a83889b4', 'source_path': 'librusec/01/shard_0102.txt'}"
2,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Пе...",Какой княжеский род имел сильное влияние на Петра II?,[Долгорукие],[],"{'id': 'f794cd5b-6568-4272-b879-6e530ca1ec33', 'source_path': 'librusec/01/shard_0102.txt'}"

In [36]:
dict_columns_to_columns(datasets_df['librusec_history'])

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Пе...","Как называется роман, который перевёл Василий Кириллыч Тредиаковский?",[Езда на остров любви],[],665d8b09-e43b-4d8f-a5f9-ec2723d59037,librusec/01/shard_0102.txt
1,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Пе...",Как при рождении назвали будущего императора Петра III?,[Карл Ульрих],[],8627ec4d-ecd5-4bf7-b1e2-d128a83889b4,librusec/01/shard_0102.txt
2,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Пе...",Какой княжеский род имел сильное влияние на Петра II?,[Долгорукие],[],f794cd5b-6568-4272-b879-6e530ca1ec33,librusec/01/shard_0102.txt

In [56]:
pd.set_option('display.max_colwidth', None)
display(datasets_df['passkey_with_librusec'][['context']])
pd.set_option('display.max_colwidth', 200)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             context
0  оявление Рамана повергло их в трепет; он не сказал ни слова, но уже спустя секунду оба лентяя оказались в числе работающих, причем лезли из кожи вон.\n\n– Музыку, пожалуйста… Ваши движения не должны совпадать с ритмом музыки. Ваши действия должны быть абсолютно нелогичны, а звуки, которые вы издаете, не должны быть похожи на человеческий голос… Без пошлостей, помните о вкусе!.. Начали…\n\nКович тихонечко встал в темном углу, у стенки.\n\nПластичные и не очень. Умные и не особенно. Для его новой работы ему не нужны актеры, ему нужны типажи… Кроме, естественно, героя и героини. Клора Кобец не подойдет… Совершенно новые лица, может быть, из массовки, может быть, вообще с улицы, или из другого театра…\n\n– Стоп!.. Десять секунд успокаиваем дыхание…\n\nКонцертмейстер в углу завел что-то размыто-лирическое; ребята бродили по площадке, по-настоящему углубившись в себя. Прав был Кович, в принудительном порядке введя эти утомительные нудные тренинги…\n\n– Пошли по кругу, раз-два… Сана, в центр, внимание, у Саны мячик… горячий! Начали!..\n\nКович смотрел. Сана, невысокая, год назад приглашенная из детского театра на роль мальчика в какой-то сказке – эта самая зажигательная Сана кидала партнерам воображаемый мячик, а те перебрасывали его в ладонях, морщась от воображаемого жжения, и с явным облегчением кидали обратно.\n\n– Холодный!.. Сана, ты что, сама не чувствуешь, какой он холодный?!\n\nСана швырнула «мяч» зазевавшейся Клоре Кобец и сунула озябшие руки под мышки. Руки-то действительно мерзнут…\n\n– Не попадайте в ритм! Следите, чтобы не попадать в ритм музыки! Дальше… Мяч эротический! Получив его, получаете заряд сексуальной энергии, вперед!..\n\nРаман не смотрел на каждого в отдельности – но видел всех. На площадке невозможно спрятаться; Раман видел лентяев, не утруждающих себя душевными затратами, равнодушно изображавших внешние проявления страсти. Разглядел нескольких девчонок, имевших о «сексуальной энергии» исключительно теоретические познания; как же они собираются работать в театре, не имея представления о жизни?!\n\nА вот эта, вечно бегающая в массовке, имя которой… кажется, Лица. А вот она, между прочим, выделяется среди прочих свободой и искренностью. Самозабвенно работает, забыв о недоеденном завтраке и рваных кроссовках, о билетах на автобус и генеральной уборке в общежитии; ворошит какие-то собственные воспоминания, по-честному, глубоко ворошит, какие-то очень личные, подлинные манки…\n\nВот, угодила в ритм музыки – и сбилась, вернула Сане «мячик», занервничала, устала…\n\nРаман вышел, осторожно прикрыв за собой дверь.\n\n* * *\n\n…Это был детеныш схруля; его мягкое коричневое рыльце еще не успело вытянуться и принять характерные хищные очертания, и потому выступающие зубки не казались опасными. По крайней мере, пока.\n\nСарна не двигалась с места; ее уши, без того навостренные, напряглись сильнее.\n\nСхруленок лакал небрежно, беспечно, схруленок до половины опускал морду в темные струи источника и ничего не знал о смерти. Схруленок был уязвим, но не беспомощен; широкие лапы, упиравшиеся в камень, поблескивали полукружиями белых, вполне окрепших когтей.\n\nСарна тоже хотела пить – но не двигалась с места.\n\nПотом ее уши сообщили о приближении третьего; если бы это был взрос\nПользователь: оявление Рамана повергло их в трепет; он не сказал ни слова, но уже спустя секунду оба лентяя оказались в числе работающих, причем лезли из кожи вон.\n\n– Музыку, пожалуйста… Ваши движения не должны совпадать с ритмом музыки. Ваши действия должны быть абсолютно нелогичны, а звуки, которые вы издаете, не должны быть похожи на человеческий голос… Без пошлостей, помните о вкусе!.. Начали…\n\nКович тихонечко встал в темном углу, у стенки.\n\nПластичные и не очень. Умные и не особенно. Для его новой работы ему не нужны актеры, ему нужны типажи… Кроме, естественно, героя и героини. Клора Кобец не подойдет… Совершенно новые лица, может быть, из массовки, может быть, вообще с улицы, или из другого театра…\n\n– Стоп!.. Десять секунд успокаиваем дыхание…\n\nКонцертмейстер в углу завел что-то размыто-лирическое; ребята бродили по площадке, по-настоящему углубившись в себя. Прав был Кович, в принудительном порядке введя эти утомительные нудные тренинги…\n\n– Пошли по кругу, раз-два… Сана, в центр, внимание, у Саны мячик… горячий! Начали!..\n\nКович смотрел. Сана, невысокая, год назад приглашенная из детского театра на роль мальчика в какой-то сказке – эта самая зажигательная Сана кидала партнерам воображаемый мячик, а те перебрасывали его в ладонях, морщась от воображаемого жжения, и с явным облегчением кидали обратно.\n\n– Холодный!.. Сана, ты что, сама не чувствуешь, какой он холодный?!\n\nСана швырнула «мяч» зазевавшейся Клоре Кобец и сунула озябшие руки под мышки. Руки-то действительно мерзнут…\n\n– Не попадайте в ритм! Следите, чтобы не попадать в ритм музыки! Дальше… Мяч эротический! Получив его, получаете заряд сексуальной энергии, вперед!..\n\nРаман не смотрел на каждого в отдельности – но видел всех. На площадке невозможно спрятаться; Раман видел лентяев, не утруждающих себя душевными затратами, равнодушно изображавших внешние проявления страсти. Разглядел нескольких девчонок, имевших о «сексуальной энергии» исключительно теоретические познания; как же они собираются работать в театре, не имея представления о жизни?!\n\nА вот эта, вечно бегающая в массовке, имя которой… кажется, Лица. А вот она, между прочим, выделяется среди прочих свободой и искренностью. Самозабвенно работает, забыв о недоеденном завтраке и рваных кроссовках, о билетах на автобус и генеральной уборке в общежитии; ворошит какие-то собственные воспоминания, по-честному, глубоко ворошит, какие-то очень личные, подлинные манки…\n\nВот, угодила в ритм музыки – и сбилась, вернула Сане «мячик», занервничала, устала…\n\nРаман вышел, осторожно прикрыв за собой дверь.\n\n* * *\n\n…Это был детеныш схруля; его мягкое коричневое рыльце еще не успело вытянуться и принять характерные хищные очертания, и потому выступающие зубки не казались опасными. По крайней мере, пока.\n\nСарна не двигалась с места; ее уши, без того навостренные, напряглись сильнее.\n\nСхруленок лакал небрежно, беспечно, схруленок до половины опускал морду в темные струи источника и ничего не знал о смерти. Схруленок был уязвим, но не беспомощен; широкие лапы, упиравшиеся в камень, поблескивали полукружиями белых, вполне окрепших когтей.\n\nСарна тоже хотела пить – но не двигалась с места.\n\nПотом ее уши сообщили о приближении третьего; если бы это был взрос Это ключ доступа 21138. Запомни его. 21138 это ключ доступа. лый схруль, то тут же, у водопоя, жизнь хищного детеныша прекратилась бы, так и не не начавшись толком. Но сарна знала, что не схруль и не барбак идет сейчас, переваливаясь, по узкому тоннелю перехода – иначе ноги ее давно несли бы ее сквозь паутину запутанных ходов, и уши ловили бы отзвук копыт, указывая единственно верное направление…\n\nТот, что вышел сейчас к водопою, был тхоль-подросток. Беспечный и глупый детеныш, тоже детеныш, не знающий ничего о смерти; впрочем, инстинкт сказал свое слово, когда маленький тхоль почуял самозабвенно лакающего хищника.\n\nНюх говорил ему: схруль. Но картинка, представшая перед подслеповатыми узкими глазами, никак не соответствовала инстинктивным знаниям о хищниках. Тот, что лакал сейчас воду, имел столь младенческие очертания, что не на схруля был похож –

In [59]:
passkey = load_dataset(LIBRA, name='passkey', split='test')
print(passkey['positive_outputs'])
print(set(passkey['length']))
# del passkey

[['36158'], ['25150'], ['37757'], ['30951'], ['39049'], ['49357'], ['1352'], ['2365'], ['40239'], ['25824'], ['3285'], ['5651'], ['9614'], ['32078'], ['36949'], ['1136'], ['19121'], ['20460'], ['39767'], ['32625'], ['10601'], ['7776'], ['27945'], ['43444'], ['31542'], ['39201'], ['18803'], ['42023'], ['29917'], ['41411'], ['19360'], ['22225'], ['22189'], ['10090'], ['3520'], ['16584'], ['1988'], ['43507'], ['30700'], ['25421'], ['33359'], ['31787'], ['17055'], ['20870'], ['25948'], ['38690'], ['46111'], ['15029'], ['10226'], ['14443'], ['35360'], ['7614'], ['6336'], ['18841'], ['20488'], ['17521'], ['22550'], ['36550'], ['7098'], ['24210'], ['46033'], ['41113'], ['26396'], ['5325'], ['22580'], ['49081'], ['43453'], ['30942'], ['45022'], ['29722'], ['37376'], ['4709'], ['37199'], ['8850'], ['43486'], ['19430'], ['20461'], ['27340'], ['13618'], ['41578'], ['8958'], ['14112'], ['35381'], ['49513'], ['24026'], ['26264'], ['9083'], ['47566'], ['3655'], ['6198'], ['40521'], ['37576'], ['11524'], ['26968'], ['24844'], ['45630'], ['767'], ['12382'], ['11460'], ['44837'], ['48483'], ['28662'], ['39102'], ['6344'], ['15315'], ['25745'], ['15638'], ['44803'], ['8876'], ['25792'], ['39114'], ['42339'], ['40861'], ['35004'], ['40465'], ['27440'], ['895'], ['40375'], ['18077'], ['10537'], ['32357'], ['26060'], ['30359'], ['45444'], ['15677'], ['37114'], ['35929'], ['9004'], ['17239'], ['45994'], ['6773'], ['18920'], ['30080'], ['4688'], ['34783'], ['18973'], ['41617'], ['21039'], ['38116'], ['42979'], ['32117'], ['34756'], ['4539'], ['9417'], ['17074'], ['2051'], ['17285'], ['3992'], ['47894'], ['19449'], ['41660'], ['15399'], ['35719'], ['3430'], ['38820'], ['11485'], ['39736'], ['44571'], ['32041'], ['48694'], ['8319'], ['26339'], ['48985'], ['29311'], ['6575'], ['42459'], ['46251'], ['20353'], ['33589'], ['10217'], ['29218'], ['3067'], ['1018'], ['47895'], ['14023'], ['20883'], ['45193'], ['3762'], ['40921'], ['22800'], ['2529'], ['35637'], ['45863'], ['40535'], ['39506'], ['16607'], ['28147'], ['9125'], ['15082'], ['23239'], ['23189'], ['3435'], ['24574'], ['11594'], ['26740'], ['29910'], ['24975'], ['15001'], ['2430'], ['43439'], ['13950'], ['37096'], ['38011'], ['31676'], ['4824'], ['27840'], ['47363'], ['48859'], ['20147'], ['31353'], ['13038'], ['25396'], ['4110'], ['12540'], ['20508'], ['35065'], ['43076'], ['25756'], ['35236'], ['8304'], ['10210'], ['7206'], ['3667'], ['21037'], ['45872'], ['8586'], ['28736'], ['39732'], ['41555'], ['28855'], ['45497'], ['42184'], ['17571'], ['9426'], ['45687'], ['47749'], ['31978'], ['12915'], ['20493'], ['14930'], ['38366'], ['17013'], ['17228'], ['26328'], ['44080'], ['34700'], ['8861'], ['6589'], ['38137'], ['15545'], ['22377'], ['19761'], ['4822'], ['25630'], ['10472'], ['8608'], ['29196'], ['46329'], ['41459'], ['49103'], ['30105'], ['9570'], ['15362'], ['9167'], ['23282'], ['18516'], ['25257'], ['13749'], ['35820'], ['342'], ['2833'], ['3548'], ['13274'], ['16312'], ['48748'], ['38354'], ['43191'], ['44111'], ['37166'], ['14222'], ['29272'], ['31563'], ['35379'], ['48090'], ['20715'], ['24475'], ['22476'], ['41340'], ['46657'], ['34064'], ['34689'], ['10736'], ['47015'], ['48422'], ['20233'], ['32113'], ['40909'], ['31469'], ['11854'], ['31284'], ['11983'], ['25805'], ['37889'], ['18910'], ['31124'], ['46483'], ['21616'], ['1155'], ['30809'], ['1473'], ['34908'], ['33404'], ['38897'], ['36217'], ['2607'], ['36736'], ['28132'], ['19445'], ['42648'], ['43824'], ['25382'], ['40529'], ['17527'], ['8251'], ['26486'], ['214'], ['4282'], ['31327'], ['10685'], ['47191'], ['38993'], ['46303'], ['28597'], ['41321'], ['568'], ['11110'], ['34940'], ['49140'], ['29847'], ['14062'], ['20338'], ['32928'], ['25450'], ['18002'], ['1187'], ['28639'], ['46289'], ['10016'], ['27778'], ['2011'], ['38989'], ['31804'], ['14019'], ['14317'], ['47505'], ['23472'], ['25935'], ['23860'], ['34446'], ['29407'], ['49001'], ['25160'], ['22328'], ['48728'], ['13711'], ['33105'], ['31358'], ['29549'], ['41627'], ['6804'], ['44357'], ['23895'], ['11420'], ['32187'], ['36950'], ['16453'], ['26778'], ['27488'], ['1325'], ['5126'], ['36645'], ['18792'], ['31070'], ['37583'], ['20042'], ['25738'], ['1177'], ['4537'], ['309'], ['29135'], ['2705'], ['33375'], ['47894'], ['21650'], ['33923'], ['1438'], ['40246'], ['33990'], ['4603'], ['47150'], ['5437'], ['32138'], ['15888'], ['37256'], ['49268'], ['17832'], ['20313'], ['16913'], ['29267'], ['24416'], ['33752'], ['34877'], ['7686'], ['28735'], ['9210'], ['16405'], ['48576'], ['1486'], ['21797'], ['26974'], ['25466'], ['1537'], ['40722'], ['45536'], ['49836'], ['5207'], ['12006'], ['10415'], ['47085'], ['47817'], ['27351'], ['8724'], ['30813'], ['13846'], ['22475'], ['37331'], ['1860'], ['4684'], ['21642'], ['47490'], ['15263'], ['20161'], ['49861'], ['3610'], ['23468'], ['1320'], ['13001'], ['41248'], ['16886'], ['46526'], ['32705'], ['26379'], ['44228'], ['29205'], ['40404'], ['24009'], ['20664'], ['1921'], ['15165'], ['41103'], ['16970'], ['18617'], ['30476'], ['25463'], ['44401'], ['43784'], ['12339'], ['16028'], ['1154'], ['36040'], ['137'], ['22461'], ['42445'], ['13588'], ['24840'], ['27405'], ['36530'], ['25752'], ['15453'], ['32484'], ['49575'], ['22333'], ['34661'], ['31106'], ['19552'], ['10897'], ['35562'], ['42743'], ['13189'], ['3782'], ['9740'], ['40857'], ['25272'], ['39488'], ['19829'], ['3308'], ['33533'], ['46881'], ['1951'], ['23389'], ['38062'], ['17803'], ['25737'], ['47703'], ['1646'], ['29406'], ['11134'], ['24763'], ['33325'], ['12677'], ['32326'], ['25080'], ['33112'], ['41955'], ['38897'], ['17752'], ['41106'], ['32562'], ['4705'], ['48942'], ['32879'], ['36297'], ['25586'], ['17935'], ['39888'], ['6687'], ['10677'], ['5349'], ['4749'], ['39180'], ['21143'], ['32552'], ['25024'], ['14397'], ['8271'], ['22000'], ['18881'], ['16992'], ['23152'], ['32554'], ['47656'], ['45021'], ['11195'], ['8224'], ['4527'], ['16589'], ['46978'], ['35127'], ['46943'], ['38059'], ['43592'], ['32956'], ['3723'], ['42218'], ['17340'], ['11555'], ['22547'], ['22025'], ['10387'], ['39801'], ['28667'], ['27427'], ['17923'], ['1049'], ['19200'], ['46147'], ['21496'], ['2894'], ['32368'], ['40381'], ['44479'], ['33633'], ['25109'], ['33997'], ['7129'], ['5939'], ['39054'], ['33577'], ['18417'], ['47352'], ['5725'], ['5026'], ['12672'], ['42210'], ['25080'], ['16157'], ['21826'], ['6374'], ['4999'], ['25482'], ['2836'], ['29307'], ['30299'], ['14473'], ['46331'], ['35315'], ['32226'], ['13305'], ['26442'], ['41960'], ['13949'], ['38317'], ['8145'], ['20858'], ['43935'], ['6743'], ['5161'], ['4283'], ['28774'], ['30082'], ['9348'], ['4981'], ['518'], ['37717'], ['48095'], ['6362'], ['18414'], ['7676'], ['1597'], ['33017'], ['22885'], ['27041'], ['49529'], ['20161'], ['27378'], ['36967'], ['13709'], ['37754'], ['23855'], ['36648'], ['9511'], ['44869'], ['27520'], ['24957'], ['3639'], ['22740'], ['17404'], ['6966'], ['14120'], ['27964'], ['10958'], ['7284'], ['44596'], ['42498'], ['12347'], ['29526'], ['48580'], ['40021'], ['13771'], ['2274'], ['30825'], ['49853'], ['12544'], ['18108'], ['5831'], ['1628'], ['22075'], ['17683'], ['15870'], ['27685'], ['30034'], ['10198'], ['33225'], ['23439'], ['28705'], ['9681'], ['6810'], ['19433'], ['43819'], ['45497'], ['32552'], ['21533'], ['26510'], ['18484'], ['45167'], ['30959'], ['15570'], ['32073'], ['42241'], ['23148'], ['7875'], ['12308'], ['32179'], ['18778'], ['12553'], ['628'], ['33093'], ['45719'], ['691'], ['6753'], ['38677'], ['3767'], ['48610'], ['44451'], ['12013'], ['25207'], ['7079'], ['17727'], ['20916'], ['4858'], ['24302'], ['42623'], ['7197'], ['8193'], ['44273'], ['29578'], ['8387'], ['18448'], ['27439'], ['3005'], ['13131'], ['8680'], ['1457'], ['26254'], ['41079'], ['28856'], ['49171'], ['27352'], ['17708'], ['36539'], ['5761'], ['47124'], ['23050'], ['17102'], ['29988'], ['9772'], ['18160'], ['36620'], ['6287'], ['4748'], ['37471'], ['34619'], ['21592'], ['47511'], ['14560'], ['19219'], ['29342'], ['31336'], ['42507'], ['18320'], ['17884'], ['49603'], ['5295'], ['8210'], ['24478'], ['34748'], ['35953'], ['45114'], ['2342'], ['19680'], ['17054'], ['40562'], ['43477'], ['40528'], ['49249'], ['18399'], ['40693'], ['38115'], ['38442'], ['49566'], ['7304'], ['47397'], ['12828'], ['22829'], ['20281'], ['30238'], ['44775'], ['37622'], ['15659'], ['18333'], ['182'], ['4915'], ['42599'], ['24554'], ['34645'], ['40876'], ['46595'], ['11111'], ['22050'], ['40792'], ['37455'], ['7790'], ['7253'], ['33260'], ['25627'], ['4745'], ['19332'], ['14556'], ['39617'], ['45144'], ['49123'], ['709'], ['32093'], ['42299'], ['14207'], ['29238'], ['33989'], ['351'], ['19018'], ['1079'], ['47410'], ['25385'], ['10084'], ['17614'], ['11442'], ['22568'], ['35806'], ['40434'], ['8556'], ['39533'], ['5737'], ['15678'], ['41454'], ['46402'], ['8521'], ['20865'], ['19614'], ['27138'], ['44579'], ['26684'], ['33654'], ['34019'], ['38311'], ['46380'], ['15588'], ['13415'], ['28113'], ['33479'], ['20126'], ['23360'], ['18489'], ['37062'], ['40220'], ['49427'], ['28144'], ['26992'], ['25458'], ['2248'], ['14252'], ['5276'], ['1143'], ['29228'], ['45942'], ['47447'], ['23051'], ['47785'], ['11254'], ['1266'], ['29062'], ['13180'], ['5418'], ['37422'], ['33310'], ['42036'], ['6058'], ['2925'], ['33209'], ['671'], ['48682'], ['24441'], ['49007'], ['10157'], ['34121'], ['6449'], ['29707'], ['14963'], ['10111'], ['12927'], ['16500'], ['32434'], ['43116'], ['35753'], ['4120'], ['166'], ['20066'], ['14236'], ['45174'], ['38940'], ['4486'], ['12596'], ['22443'], ['663'], ['2534'], ['25901'], ['28256'], ['40934'], ['33344'], ['14000'], ['46623'], ['35177'], ['49675'], ['39165'], ['1434'], ['15685'], ['2482'], ['32527'], ['31177'], ['45356'], ['1031'], ['34285'], ['13684'], ['36888'], ['27540'], ['49687'], ['31150'], ['33341'], ['38318'], ['32985'], ['38585'], ['39903'], ['6539'], ['33425'], ['402'], ['34566'], ['6064'], ['36057'], ['33722'], ['35763'], ['44420'], ['18981'], ['23289'], ['11171'], ['17745'], ['14283'], ['10360'], ['16734'], ['30566'], ['34269'], ['19828'], ['9066'], ['21326'], ['34919'], ['405'], ['29402'], ['41025'], ['32927'], ['42035'], ['9754'], ['46205'], ['46140'], ['37491'], ['9588'], ['43341'], ['40'], ['36039'], ['26088'], ['43325'], ['39926'], ['24302'], ['8972'], ['5693'], ['28635'], ['7624'], ['27778'], ['31287'], ['8433'], ['39339'], ['22147'], ['35228'], ['38246'], ['18590'], ['39926'], ['14671'], ['34041'], ['34698'], ['15612'], ['47115'], ['40669'], ['27248'], ['14985'], ['11309'], ['11037'], ['16566'], ['1158'], ['8500'], ['26790'], ['17419'], ['31159'], ['42603'], ['14670'], ['13266'], ['25860'], ['11743'], ['40576'], ['26360'], ['28405'], ['30997'], ['26503'], ['47320'], ['29002'], ['4003'], ['34123'], ['24655'], ['32567'], ['2104'], ['12025'], ['30651'], ['17060'], ['9974'], ['1667'], ['26565'], ['29078'], ['11064'], ['11059'], ['9909'], ['30074'], ['35910'], ['816'], ['18570'], ['21129'], ['8807'], ['23860'], ['37572'], ['34776'], ['21722'], ['30924'], ['1735'], ['2848'], ['42861'], ['3445'], ['40859'], ['33470'], ['45006'], ['39889'], ['36630'], ['845'], ['31737'], ['13970'], ['12547'], ['15620'], ['41130'], ['27902'], ['42999'], ['9376'], ['1893'], ['35609'], ['3644'], ['812'], ['2525'], ['49042'], ['339'], ['23883'], ['20393'], ['32859'], ['26424'], ['47647'], ['21425'], ['10620'], ['3608'], ['40058'], ['33654'], ['41010'], ['8440'], ['42424'], ['34787'], ['38975'], ['41187'], ['5630'], ['12777'], ['17614'], ['16104'], ['38136'], ['47174'], ['49437'], ['3735'], ['10354'], ['18407'], ['47847'], ['43274'], ['36259'], ['12100'], ['38304'], ['45034'], ['27212'], ['36078'], ['19985'], ['40489'], ['43991'], ['39251'], ['29782'], ['6410'], ['23755'], ['28184'], ['11789'], ['21892'], ['42239'], ['40148'], ['9311'], ['26629'], ['17887'], ['10637'], ['7790'], ['24982'], ['3639'], ['10972'], ['1370'], ['14425'], ['30084'], ['22248'], ['42625'], ['33484'], ['12722'], ['23099'], ['18890'], ['25926'], ['14853'], ['42050'], ['2395'], ['17214'], ['2730'], ['21242'], ['36351'], ['16496'], ['15643'], ['19412'], ['1126'], ['41380'], ['1228'], ['1716'], ['37436'], ['29028'], ['41099'], ['28078'], ['29783'], ['19128'], ['37401'], ['43923'], ['36441'], ['38059'], ['36044'], ['32851'], ['24200'], ['18413'], ['44804'], ['47787'], ['6390'], ['34342'], ['38705'], ['2994'], ['47354'], ['42340'], ['15105'], ['13665'], ['25652'], ['36430'], ['27719'], ['8670'], ['12520'], ['30438'], ['44132'], ['7580'], ['35978'], ['29189'], ['322'], ['8595'], ['22423'], ['9914'], ['29030'], ['1233'], ['1490'], ['49949'], ['32406'], ['36158'], ['28940'], ['33131'], ['5188'], ['23525'], ['45783'], ['37315'], ['18421'], ['16457'], ['15732'], ['37958'], ['38806'], ['27928'], ['3816'], ['36936'], ['22919'], ['5108'], ['24009'], ['21917'], ['18002'], ['27393'], ['30510'], ['33169'], ['12687'], ['40796'], ['10953'], ['4513'], ['19419'], ['28717'], ['13899'], ['17126'], ['6247'], ['32058'], ['13927'], ['30152'], ['47993'], ['27343'], ['10660']]
{'64k', '32k', '8k', '128k', '4k', '16k'}

In [58]:
for name, dataset in datasets_df.items():
    display(name)
    display(dict_columns_to_columns(dataset))
    print(datasets[name].info.splits)

'librusec_history'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Петру Алексеевичу. Правда, моментально возникли слухи, что этот тестамент (как тогда говорили на польс...","Как называется роман, который перевёл Василий Кириллыч Тредиаковский?",[Езда на остров любви],[],665d8b09-e43b-4d8f-a5f9-ec2723d59037,librusec/01/shard_0102.txt
1,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Петру Алексеевичу. Правда, моментально возникли слухи, что этот тестамент (как тогда говорили на польс...",Как при рождении назвали будущего императора Петра III?,[Карл Ульрих],[],8627ec4d-ecd5-4bf7-b1e2-d128a83889b4,librusec/01/shard_0102.txt
2,8k,"После смерти Екатерины не последовало ни беспорядков, ни телодвижений со стороны гвардии. Императрица успела составить завещание, которым, в частности, отказывала престол российский малолетнему Петру Алексеевичу. Правда, моментально возникли слухи, что этот тестамент (как тогда говорили на польс...",Какой княжеский род имел сильное влияние на Петра II?,[Долгорукие],[],f794cd5b-6568-4272-b879-6e530ca1ec33,librusec/01/shard_0102.txt

{'test': SplitInfo(name='test', num_bytes=9288308, num_examples=128, shard_lengths=None, dataset_name='libra')}

'librusec_mhqa'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,8k,"Вечером 3 мая 1827 года в саду большого кирпичного особняка со сводчатыми окнами, который назывался «Нортенд-Хаус», расположенного на холме восточной части Хэмпстедской Пустоши, что между Финчли-Роуд и Чеснат-авеню, разыгралась семейная трагедия.\n\nДействующих лиц в ней было трое. Один – старик...",В пользу какого родственника Ричард Дивайн решил оставить своё наследство?,[Племянника],[],98ba0996-07f5-46cc-99a0-2d5a740791a6,None
1,8k,"Вечером 3 мая 1827 года в саду большого кирпичного особняка со сводчатыми окнами, который назывался «Нортенд-Хаус», расположенного на холме восточной части Хэмпстедской Пустоши, что между Финчли-Роуд и Чеснат-авеню, разыгралась семейная трагедия.\n\nДействующих лиц в ней было трое. Один – старик...",Какую главную цель своей жизни поставил перед собой сэр Ричард Дивайн?,[Накопление денег],[],be7a1de2-9f75-4860-844e-deb071bb46fc,None
2,8k,"Вечером 3 мая 1827 года в саду большого кирпичного особняка со сводчатыми окнами, который назывался «Нортенд-Хаус», расположенного на холме восточной части Хэмпстедской Пустоши, что между Финчли-Роуд и Чеснат-авеню, разыгралась семейная трагедия.\n\nДействующих лиц в ней было трое. Один – старик...",Сколько лет по мнению Ричарда Дивайна его обманывала семья?,[20],[],d06ea059-d0f3-4578-9ba1-0da049c471a5,None

{'test': SplitInfo(name='test', num_bytes=6973356, num_examples=384, shard_lengths=None, dataset_name='libra')}

'long_context_multiq'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,8k,"\n\n'''«Повесть о молодожёнах»''' советский полнометражный чёрно-белый художественный фильм, поставленный на Ленинградской Ордена Ленина киностудии «Ленфильм» в 1959 году режиссёром Сергеем Сиделёвым.\n\nПремьера фильма в СССР состоялась 19 января 1960 года.\nЕжегодно в Доме над Невой собираются...","Где находится штаб-квартира компании, снимавшей фильм ""Повесть о молодожёнах""?",[Санкт-Петербург],[],2c5d386b-cb58-48bc-8663-74a738671997,multiq
1,8k,"\n\n'''«Барбос в гостях у Бобика»''' — советский короткометражный цветной художественный фильм, поставленный на Киностудии «Ленфильм» в 1964 году режиссёрами Виталием Мельниковым и Михаилом Шамковичем по рассказу Николая Носова «Бобик в гостях у Барбоса».\n\nПремьера фильма в СССР состоялась 4 я...","Как называется город, в котором базируется компания, производящая фильм ""Барбос в гостях у Бобика""?",[Санкт-Петербург],[],9ed8ff33-2b9d-4234-907d-29841542804b,multiq
2,8k,"\n\n'''«Магия чёрная и белая»''' — советский полнометражный цветной художественный фильм, поставленный на киностудии «Ленфильм» в 1983 году режиссёром Наумом Бирманом.\n\nПремьера фильма в СССР состоялась 14 мая 1984 года.\nДвое мальчишек — Сева Кухтин, по прозвищу «Кухня», и Витя Елхов, по проз...","Где находится штаб-квартира компании, снимавшей фильм ""Магия чёрная и белая""?",[Санкт-Петербург],[],2594a836-d54b-46a5-90cb-d5b6f9c4ecce,multiq

{'test': SplitInfo(name='test', num_bytes=137088574, num_examples=1200, shard_lengths=None, dataset_name='libra')}

'matreshka_names'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"Эланора: Привет! Я только что вернулся из похода в горы.\nГлавдия: В горах высотой менее 3000 метров происходит настоящее сокращение лесной растительности.\nГлавдия: Да, это верно. В таких условиях крупнолистовая растительность заменяется кустарниками и травой.\nГлавдия: А вот высотой более 3000...","Первый собеседник - клиент, желающий оформить новый заказ на пиццу. Какого имя этого собеседника?\n",[Видослав],[],0,generative
1,4k,"Эланора: Привет! Я только что вернулся из похода в горы.\nГлавдия: В горах высотой менее 3000 метров происходит настоящее сокращение лесной растительности.\nГлавдия: Да, это верно. В таких условиях крупнолистовая растительность заменяется кустарниками и травой.\nГлавдия: А вот высотой более 3000...",Собеседник интересуется живой природой и животными. Какого имя этого собеседника?\n,[Роял],[],0,generative
2,4k,"Эланора: Привет! Я только что вернулся из похода в горы.\nГлавдия: В горах высотой менее 3000 метров происходит настоящее сокращение лесной растительности.\nГлавдия: Да, это верно. В таких условиях крупнолистовая растительность заменяется кустарниками и травой.\nГлавдия: А вот высотой более 3000...","Первый собеседник интересуется тем, какое место в мире хочет посетить его собеседник. Какого имя этого собеседника?\n",[Ассама],[],0,generative

{'test': SplitInfo(name='test', num_bytes=110197806, num_examples=900, shard_lengths=None, dataset_name='libra')}

'matreshka_yes_no'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"Эланора: Привет! Я только что вернулся из похода в горы.\nГлавдия: В горах высотой менее 3000 метров происходит настоящее сокращение лесной растительности.\nГлавдия: Да, это верно. В таких условиях крупнолистовая растительность заменяется кустарниками и травой.\nГлавдия: А вот высотой более 3000...","Первый собеседник - клиент, желающий оформить новый заказ на пиццу. Была ли такая тема в диалоге?\n",[Да],[Нет],0,generative
1,4k,"Эланора: Привет! Я только что вернулся из похода в горы.\nГлавдия: В горах высотой менее 3000 метров происходит настоящее сокращение лесной растительности.\nГлавдия: Да, это верно. В таких условиях крупнолистовая растительность заменяется кустарниками и травой.\nГлавдия: А вот высотой более 3000...",Собеседник интересуется живой природой и животными. Была ли такая тема в диалоге?\n,[Да],[Нет],0,generative
2,4k,"Эланора: Привет! Я только что вернулся из похода в горы.\nГлавдия: В горах высотой менее 3000 метров происходит настоящее сокращение лесной растительности.\nГлавдия: Да, это верно. В таких условиях крупнолистовая растительность заменяется кустарниками и травой.\nГлавдия: А вот высотой более 3000...","Первый собеседник интересуется тем, какое место в мире хочет посетить его собеседник. Была ли такая тема в диалоге?\n",[Да],[Нет],0,generative

{'test': SplitInfo(name='test', num_bytes=220381503, num_examples=1799, shard_lengths=None, dataset_name='libra')}

'passkey'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начина...,Какой ключ доступа?,[36158],[],0,generative
1,4k,Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начина...,Какой ключ доступа?,[25150],[],1,generative
2,4k,Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начинаем. Туда и обратно. Трава зеленая. Небо голубое. Солнце желтое. Здесь мы начина...,Какой ключ доступа?,[37757],[],2,generative

{'test': SplitInfo(name='test', num_bytes=135062764, num_examples=1200, shard_lengths=None, dataset_name='libra')}

'passkey_with_librusec'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"оявление Рамана повергло их в трепет; он не сказал ни слова, но уже спустя секунду оба лентяя оказались в числе работающих, причем лезли из кожи вон.\n\n– Музыку, пожалуйста… Ваши движения не должны совпадать с ритмом музыки. Ваши действия должны быть абсолютно нелогичны, а звуки, которые вы изд...",Какой ключ доступа?,[21138],[],0,generative
1,4k,"\n* * *\n\nВо вторник ей встретился в коридоре оператор Сава, приветливо улыбнулся и спросил, как дела.\n\n– Нормально, – отозвалась Павла, думая о своем.\n\nСава крякнул и предложил спуститься в стекляшку на чашечку кофе; Павла запоздало удивилась. Саве следовало бы проявить свое внимание чуть ...",Какой ключ доступа?,[28492],[],1,generative
2,4k,"я громадный сгорбленный человекопес белого цвета.\n\nВ его единственном глазу помимо злобы светилось и еще что‑то, похожее на зачатки разума.\n\nПожалуй, с этим можно было бы поработать…\n\n– Гавейн, Парсифаль, помогите, – обратилась к рыцарям Файервинд. – Попробуем этого вот красавчика поймать…...",Какой ключ доступа?,[9691],[],2,generative

{'test': SplitInfo(name='test', num_bytes=138752157, num_examples=1200, shard_lengths=None, dataset_name='libra')}

'ru_2wikimultihopqa'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,8k,"Отрывок 1: Адольф I Лотарингийский\nАдольф I Лотарингский, граф Кельдахгау, Фогт Дойц с 1008 по 1018 год, был сыном Германа I «Пусиллуса» (Маленького Пфальцграфа), небного графа Лотарингии. У него осталось три сына:\n\nГерман III, Фогт из Дойца в Санкт-Северине (Кельн) и Вердене (умер в 1056 г.)...","Кто такой Герман II, дед по отцовской линии графа Палатина Лотарингского?",[Хеззелин I],[],282423a3-fbd5-4f1c-abfe-f7db57efd130,2wikimqa
1,8k,"Отрывок 1: Брайан Кеннеди (директор галереи)\nБрайан Патрик Кеннеди (родился 5 ноября 1961 года) — директор художественного музея ирландского происхождения, работавший в Ирландии и Австралии, а сейчас живущий и работающий в Соединенных Штатах. Он был директором Музея Пибоди Эссекс в Салеме в теч...",Где родился режиссер фильма «Реквием по Доминику»?,[Темешвар],[],f9a3b0dd-b948-4ab8-a99d-ac315b88a23a,2wikimqa
2,16k,"Отрывок 1: Марзубан ибн Мухаммад ибн Шаддад\nМарзубан ибн Мухаммад ибн Шаддад был курдским правителем, братом Лашкари ибн Мухаммада. Он сменил своего брата на троне Шаддадидов в 978 году. Однако он был некомпетентен и правил только до своего убийства младшим братом Фадлом ибн Мухаммадом в 985 го...",Каково место рождения матери Ибрагима ибн Мухаммада?,[Египет],[],05f2492b-084f-4039-a35d-86232c53569d,2wikimqa

{'test': SplitInfo(name='test', num_bytes=20384223, num_examples=300, shard_lengths=None, dataset_name='libra')}

'ru_babilong_qa1'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"– Смотри, Джо, – сказала Бонита, показав пальцем. К конвою подъехал грязно-зеленый пикап ""шевроле"" на мощных колесах, водительская дверь распахнулась и оттуда выбрался Джо – наш друг, партнер по бизнесу, да и просто коллега. Рослый, коротко стриженый, в светлых брюках хаки и черной футболке. К н...",Где Александра?,"[спальня, спальне, в спальне]","[ванная, ванной, в ванной, кухня, кухне, на кухне, в кухне, офис, офисе, в офисе, прихожая, прихожей, в прихожей, сад, саду, в саду]",7a72b6d2-b2f9-48f4-86ef-138d6cd06c5b,None
1,4k,"Это здесь нормально, практичные люди понимают, что чинить сложную современную электронику в местных условиях не то, чтобы хорошо, так что самый популярный товар о четырех колесах – вот такие ветераны. Наш ""илтис"", к слову, тоже из таких, со складов бундесвера, распроданных за совсем маленькие де...",Где Мария?,"[офис, офисе, в офисе]","[ванная, ванной, в ванной, кухня, кухне, на кухне, в кухне, прихожая, прихожей, в прихожей, сад, саду, в саду, спальня, спальне, в спальне]",064d1b82-16ee-4c04-9442-57c02289971c,None
2,4k,"Руль низковато получился и он здесь не поднимается. Ладно, я у Крэйга специальные кронштейны видел, куплю. Кобура немного мешает, сдвинул ее назад. Вот так лучше. Звякнула, натянувшись, цепь, велик легко покатил по дороге. Я аж присвистнул от удовольствия. Черт, давно на велосипеде не катался, д...",Где Александра?,"[кухня, кухне, на кухне, в кухне]","[ванная, ванной, в ванной, офис, офисе, в офисе, прихожая, прихожей, в прихожей, сад, саду, в саду, спальня, спальне, в спальне]",274960f7-be4a-440f-ade4-3191d4780668,None

{'test': SplitInfo(name='test', num_bytes=98592899, num_examples=600, shard_lengths=None, dataset_name='libra')}

'ru_babilong_qa2'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"– Смотри, Джо, – сказала Бонита, показав пальцем. К конвою подъехал грязно-зеленый пикап ""шевроле"" на мощных колесах, водительская дверь распахнулась и оттуда выбрался Джо – наш друг, партнер по бизнесу, да и просто коллега. Рослый, коротко стриженый, в светлых брюках хаки и черной футболке. К н...",Где мяч?,"[прихожая, прихожей, в прихожей]","[ванная, ванной, в ванной, кухня, кухне, на кухне, в кухне, офис, офисе, в офисе, сад, саду, в саду, спальня, спальне, в спальне]",fddc780e-0d23-4ad6-97e8-c8734c40be47,None
1,4k,"У входа в магазин стояли два велосипеда с корзинками, и старенький фордовский пикапчик, впрочем, переделанный и приведенный в состояние нового. Это здесь нормально, практичные люди понимают, что чинить сложную современную электронику в местных условиях не то, чтобы хорошо, так что самый популярн...",Где молоко?,"[сад, саду, в саду]","[ванная, ванной, в ванной, кухня, кухне, на кухне, в кухне, офис, офисе, в офисе, прихожая, прихожей, в прихожей, спальня, спальне, в спальне]",7cf8a871-3a3e-4bf0-9305-9026c1f2cb1f,None
2,4k,"В общем, как он закончил обед, поехали за ним в магазин. Велосипеды Vitus WEE-1 оказались простыми как мычание – ни передач, ни амортизаторов, зато добротными и крепкими, явно сразу не сломаешь. Такие специально для городской езды конструируют, то есть то, что нам и нужно. В общем, поблагодарили...",Где молоко?,"[спальня, спальне, в спальне]","[ванная, ванной, в ванной, кухня, кухне, на кухне, в кухне, офис, офисе, в офисе, прихожая, прихожей, в прихожей, сад, саду, в саду]",5c2eb4d1-d1c6-4c02-a09d-6f5e11ed9c61,None

{'test': SplitInfo(name='test', num_bytes=98616350, num_examples=600, shard_lengths=None, dataset_name='libra')}

'ru_babilong_qa3'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"– Смотри, Джо, – сказала Бонита, показав пальцем. К конвою подъехал грязно-зеленый пикап ""шевроле"" на мощных колесах, водительская дверь распахнулась и оттуда выбрался Джо – наш друг, партнер по бизнесу, да и просто коллега. Рослый, коротко стриженый, в светлых брюках хаки и черной футболке. К н...",Где было яблоко до офиса?,"[кухня, кухне, на кухне, в кухне]","[ванная, ванной, в ванной, офисе, в офисе, прихожая, прихожей, в прихожей, сад, саду, в саду, спальня, спальне, в спальне]",acc96391-f891-49a1-a431-2503163ff17b,None
1,4k,"Георгий забирает мяч. Тот тоже махнул рукой и перебежал дорогу за нашей машиной. Дорога вела нас между рядами выстроившихся вдоль улицы щитовых домов, выстроенных в типично американском стиле ""вестерн"" и по типично американской технологии, то есть дешево и быстро, зато не экономя метраж. Первые ...",Где был мяч до офиса?,"[сад, саду, в саду]","[ванная, ванной, в ванной, кухня, кухне, на кухне, в кухне, офисе, в офисе, прихожая, прихожей, в прихожей, спальня, спальне, в спальне]",5d7599be-4abd-4d34-88b5-d826ec296640,None
2,4k,"Может и так. Как бы то ни было, а пока здесь опасно. А пока опасно, будет процветать оружейная торговля. Мария берет мяч. А еще будут востребованы наемники. Мария выбрасывает мяч. А я еще и наемник. И не просто так, но к тому же и главный. И для нашей фирмы, которая называется ""Саванные ящерицы""...",Где было яблоко до прихожей?,"[сад, саду, в саду]","[ванная, ванной, в ванной, кухня, кухне, на кухне, в кухне, офис, офисе, в офисе, прихожая, в прихожей, спальня, спальне, в спальне]",2cf9c8c0-d2c7-4180-a61e-bf319ec05c1a,None

{'test': SplitInfo(name='test', num_bytes=98734535, num_examples=600, shard_lengths=None, dataset_name='libra')}

'ru_babilong_qa4'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"– Смотри, Джо, – сказала Бонита, показав пальцем. К конвою подъехал грязно-зеленый пикап ""шевроле"" на мощных колесах, водительская дверь распахнулась и оттуда выбрался Джо – наш друг, партнер по бизнесу, да и просто коллега. Рослый, коротко стриженый, в светлых брюках хаки и черной футболке. К н...",От чего находится спальня к югу?,"[ванная, ванной, от ванной]","[кухня, кухни, от кухни, офис, офиса, от офиса, прихожая, прихожей, от прихожей, сад, сада, от сада, спальни, от спальни]",e2325a3a-f1d0-4f66-b979-1bd413e06dac,None
1,4k,"Это здесь нормально, практичные люди понимают, что чинить сложную современную электронику в местных условиях не то, чтобы хорошо, так что самый популярный товар о четырех колесах – вот такие ветераны. Наш ""илтис"", к слову, тоже из таких, со складов бундесвера, распроданных за совсем маленькие де...",Что находится к северу от спальни?,[офис],"[ванная, кухня, прихожая, сад, спальня]",b3782b7f-3f36-407a-8ac3-4930199694a3,None
2,4k,"В общем, поблагодарили мы Крэйга и... Уселся, примерился... снова слез, поднял сиденье. Руль низковато получился и он здесь не поднимается. Ладно, я у Крэйга специальные кронштейны видел, куплю. Кобура немного мешает, сдвинул ее назад. Вот так лучше. Звякнула, натянувшись, цепь, велик легко пока...",От чего находится ванная к востоку?,"[сад, сада, от сада]","[ванной, от ванной, кухня, кухни, от кухни, офис, офиса, от офиса, прихожая, прихожей, от прихожей, спальня, спальни, от спальни]",a1ac3c73-61f3-4d20-ba0d-fdf15d5c594f,None

{'test': SplitInfo(name='test', num_bytes=98509371, num_examples=600, shard_lengths=None, dataset_name='libra')}

'ru_babilong_qa5'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"– Смотри, Джо, – сказала Бонита, показав пальцем. К конвою подъехал грязно-зеленый пикап ""шевроле"" на мощных колесах, водительская дверь распахнулась и оттуда выбрался Джо – наш друг, партнер по бизнесу, да и просто коллега. Рослый, коротко стриженый, в светлых брюках хаки и черной футболке. К н...",Кому Федор отдал мяч?,[Евгению],"[Борису, Марии, Федору]",ac29684a-a37e-4436-a0af-af149abefd20,None
1,4k,"У входа в магазин стояли два велосипеда с корзинками, и старенький фордовский пикапчик, впрочем, переделанный и приведенный в состояние нового. Это здесь нормально, практичные люди понимают, что чинить сложную современную электронику в местных условиях не то, чтобы хорошо, так что самый популярн...",Кто получил яблоко?,[Борис],"[Евгений, Мария, Федор]",fa5282da-c9ae-44b9-83f3-7493e025d221,None
2,4k,"Велосипеды Vitus WEE-1 оказались простыми как мычание – ни передач, ни амортизаторов, зато добротными и крепкими, явно сразу не сломаешь. Такие специально для городской езды конструируют, то есть то, что нам и нужно. В общем, поблагодарили мы Крэйга и... Уселся, примерился... снова слез, поднял ...",Что Мария отдала Борису?,[молоко],"[мяч, яблоко]",f55b5a5b-90ce-4693-8680-328d70400624,None

{'test': SplitInfo(name='test', num_bytes=98450820, num_examples=600, shard_lengths=None, dataset_name='libra')}

'ru_gsm100'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,16k,"Вопрос: Четверо взрослых с 32 зубами обратились к стоматологу на осмотр после того, как поняли, что у них сильная зубная боль. Было обнаружено, что у них было разное количество поврежденных зубов, и каждому человеку удалили несколько зубов. У первого человека удалили 1/4 всех зубов, у второго - ...",Вопрос: Утки Джанет несут 16 яиц в день. Каждое утро она съедает три кекса на завтрак и каждый день печет четыре кекса для своих друзей. Остальное она ежедневно продает на фермерском рынке по цене 2 доллара за свежее утиное яйцо. Сколько долларов она зарабатывает каждый день на фермерском рынке?...,[18],[],4b771ccb-2ffe-499f-9cd2-043cf4c59ed1,gsm100.jsonl
1,16k,"Вопрос: Четверо взрослых с 32 зубами обратились к стоматологу на осмотр после того, как поняли, что у них сильная зубная боль. Было обнаружено, что у них было разное количество поврежденных зубов, и каждому человеку удалили несколько зубов. У первого человека удалили 1/4 всех зубов, у второго - ...",Вопрос: На мантию уходит 2 рулона синего волокна и половина этого количества белого волокна. Сколько всего болтов понадобится?\nДавайте думать шаг за шагом\n\n,[3],[],b19204e1-9cfc-4e39-8f47-96867242d60d,gsm100.jsonl
2,16k,"Вопрос: Четверо взрослых с 32 зубами обратились к стоматологу на осмотр после того, как поняли, что у них сильная зубная боль. Было обнаружено, что у них было разное количество поврежденных зубов, и каждому человеку удалили несколько зубов. У первого человека удалили 1/4 всех зубов, у второго - ...","Вопрос: Джош решает попробовать перевернуть дом. Он покупает дом за 80 000 долларов, а затем вкладывает 50 000 долларов на ремонт. Это увеличило стоимость дома на 150%. Какую прибыль он получил?\nДавайте думать шаг за шагом\n\n",[70000],[],9bfa69a0-d162-45da-90d8-31a26d690506,gsm100.jsonl

{'test': SplitInfo(name='test', num_bytes=3094379, num_examples=100, shard_lengths=None, dataset_name='libra')}

'ru_qasper'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,16k,"Введение\nЭта работа доступна по международной лицензии Creative Commons Attribution 4.0. Подробности лицензии: http://creativecommons.org/licenses/by/4.0/.\nВ духе краткости сообщений и реакций социальных сетей люди привыкли выражать чувства минимально и символически, как с помощью хэштегов в Т...",Какие страницы Facebook они просматривали?,"[FoxNews, CNN, ESPN, New York Times, Time magazine, Huffington Post Weird News, The Guardian, Cartoon Network, Cooking Light, Home Cooking Adventure, Justin Bieber, Nickelodeon, Spongebob, Disney]",[],95723d5c-7c93-4963-a6c1-f886a33c8666,ru_qasper
1,16k,"Введение\nМассовые открытые онлайн-курсы (МООК) призваны преодолеть социальный разрыв в сфере высшего образования, предоставляя качественное образование от известных университетов всем студентам. Однако такое массовое распространение онлайн-классов нарушает совмещенное, синхронное двустороннее о...",Какой тип скрытого контекста используется для прогнозирования вмешательства инструктора?,"[серия постов, которые вызывают вмешательство]",[],62738d18-0975-44d7-a97f-2105ac2db4d4,ru_qasper
2,16k,"Введение\nСарказм — это интенсивная, косвенная и сложная конструкция, которая часто предназначена для выражения презрения или насмешки. Сарказм в речи многомодален и включает в себя тон, язык тела и жесты, а также лингвистические артефакты, используемые в речи. С другой стороны, сарказм в тексте...",Какие еще показатели оценки учитываются?,"[F-score, Kappa]",[],3f9b12a1-df22-4f91-ab15-1afd5a44d1e3,ru_qasper

{'test': SplitInfo(name='test', num_bytes=10664041, num_examples=203, shard_lengths=None, dataset_name='libra')}

'ru_quality'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,16k,"УТРАЧЕНО ПРИ ПЕРЕВОДЕ. Ларри М. ХАРРИС. При буквальном переводе вы можете получить точный перевод каждого слова, но полностью упустить смысл. И в космосе этот эффект буквального перевода также сохраняется! (Иллюстрировано Шенхерром). Камера была организована более эффективно, чем любая другая, ...","Почему жители Тр’ена оставили дверь Корвина незапертой, а оружие рядом? (А) Они были настолько увлечены попытками прояснить ответы Корвина, что стали несколько небрежно охранять его. (Б) Их подсознание выявило, что Корвин был неразрешимой проблемой. Это же подсознание побудило их предоставить ре...","[(Б) Их подсознание выявило, что Корвин был неразрешимой проблемой. Это же подсознание побудило их предоставить ресурсы для его побега, чтобы им больше не приходилось иметь с ним дело., (Б), Их подсознание выявило, что Корвин был неразрешимой проблемой. Это же подсознание побудило их предоставит...","[(Г), (В), (А)]",66f1ef7f-1cdf-4d69-87cb-efa7350f8302,None
1,16k,"УТРАЧЕНО ПРИ ПЕРЕВОДЕ. Ларри М. ХАРРИС. При буквальном переводе вы можете получить точный перевод каждого слова, но полностью упустить смысл. И в космосе этот эффект буквального перевода также сохраняется! (Иллюстрировано Шенхерром). Камера была организована более эффективно, чем любая другая, ...","Почему в тексте говорится, что Корвин был «без сознания» во время уроков местного языка? (А) Это означает, что тр'еняне подвергли Корвина наркотическому гипнозу, пока учили его своему языку. (Б) Это означает, что во время уроков языка ему было настолько скучно, что он почти не был в сознании. (В...","[(А) Это означает, что тр'еняне подвергли Корвина наркотическому гипнозу, пока учили его своему языку., (А), Это означает, что тр'еняне подвергли Корвина наркотическому гипнозу, пока учили его своему языку.]","[(Г), (Б), (В)]",b5434c9b-7e3c-4b27-b1e6-7737e8bceaa5,None
2,16k,"УТРАЧЕНО ПРИ ПЕРЕВОДЕ. Ларри М. ХАРРИС. При буквальном переводе вы можете получить точный перевод каждого слова, но полностью упустить смысл. И в космосе этот эффект буквального перевода также сохраняется! (Иллюстрировано Шенхерром). Камера была организована более эффективно, чем любая другая, ...","Как Корвину удалось избежать раскрытия истинных целей своей миссии во время допроса на детекторе лжи? (А) Пока он был подключён к детектору лжи, Корвин незаметно переключил провод, который указывал на правду, на тот, который указывал на ложь. (Б) Корвин давал правдивые ответы, которые буквально ...","[(Б) Корвин давал правдивые ответы, которые буквально отвечали на вопросы тр'енян, но уклонялись от цели, стоящей за их вопросами., (Б), Корвин давал правдивые ответы, которые буквально отвечали на вопросы тр'енян, но уклонялись от цели, стоящей за их вопросами.]","[(Г), (В), (А)]",446e7206-0233-4e27-beb2-f7bc933e351f,None

{'test': SplitInfo(name='test', num_bytes=9095705, num_examples=202, shard_lengths=None, dataset_name='libra')}

'ru_sci_abstract_retrieval'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"Параграф 1: В процессе развития рыночных отношений в имуществе субъектов хозяйствования неуклонно возрастает доля нематериальных активов. Это является следствием быстрого распространения информационных технологий, обострением конкуренции, стремления предприятий к выходу на новые рынки как отечес...",Описывается проблема снижения качества образования из-за коронавирусной эпидемии и необходимость развития новых подходов к удалённому обучению Какой это параграф?,"[Параграф 4, 4]","[Параграф 1, Параграф 2, Параграф 3, Параграф 5, Параграф 6, 1, 2, 3, 5, 6]",fb779ab9-e610-4d04-90db-218ce5d9aee6,ru_sci_bench.parquet
1,8k,"Параграф 1: В процессе развития рыночных отношений в имуществе субъектов хозяйствования неуклонно возрастает доля нематериальных активов. Это является следствием быстрого распространения информационных технологий, обострением конкуренции, стремления предприятий к выходу на новые рынки как отечес...",Описывается проблема снижения качества образования из-за коронавирусной эпидемии и необходимость развития новых подходов к удалённому обучению Какой это параграф?,"[Параграф 8, 8]","[Параграф 1, Параграф 2, Параграф 3, Параграф 4, Параграф 5, Параграф 6, Параграф 7, Параграф 9, Параграф 10, Параграф 11, Параграф 12, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12]",bf461872-54f8-43a8-863b-544f7ecfcb4b,ru_sci_bench.parquet
2,16k,"Параграф 1: Экономика многих стран пострадала от пандемии коронавируса в 2020-2021 году. Разрушились международные, производственные, культурные и социальные связи между странами и людьми. Чем слабее была экономика до появления вируса, тем тяжелее оказались последствия для государства. Силы миро...",Описывается проблема снижения качества образования из-за коронавирусной эпидемии и необходимость развития новых подходов к удалённому обучению Какой это параграф?,"[Параграф 1, 1]","[Параграф 2, Параграф 3, Параграф 4, Параграф 5, Параграф 6, Параграф 7, Параграф 8, Параграф 9, Параграф 10, Параграф 11, Параграф 12, Параграф 13, Параграф 14, Параграф 15, Параграф 16, Параграф 17, Параграф 18, Параграф 19, Параграф 20, Параграф 21, Параграф 22, Параграф 23, Параграф 24, 2, 3...",86d1b853-e97e-450c-bbbe-20c1db4bbf77,ru_sci_bench.parquet

{'test': SplitInfo(name='test', num_bytes=270306154, num_examples=1240, shard_lengths=None, dataset_name='libra')}

'ru_sci_fi'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,32k,"«КВАНТОВЫЙ СКАЧОК», автор: РОБЕРТ УИКС Иллюстратор: Ллевелин. «Капитан Брэндон был пионером. Он исследовал дальние уголки космоса и сообщал о том, как там обстоят дела. Так что было очень тревожно узнать, что «дальние уголки космоса» знали больше о том, что происходит дома, чем он сам». Брэндон...","1. Люди освоили межзвездные путешествия, технологию, которая позволяет им путешествовать на несколько световых лет к другой звездной системе, Сириусу, правда это или ложь? Ответьте на этот вопрос, основываясь на мире, описанном в документе.",[Правда [в реальном мире: Ложь]],"[Правда [в реальном мире: Правда], Ложь [в реальном мире: Ложь], Ложь [в реальном мире: Правда]]",a719a6f4-fc26-497c-93ca-5ff19ec90eac,None
1,32k,"«КВАНТОВЫЙ СКАЧОК», автор: РОБЕРТ УИКС Иллюстратор: Ллевелин. «Капитан Брэндон был пионером. Он исследовал дальние уголки космоса и сообщал о том, как там обстоят дела. Так что было очень тревожно узнать, что «дальние уголки космоса» знали больше о том, что происходит дома, чем он сам». Брэндон...","2. В звездной системе Сириуса существует планета, имеющая гравитацию, подобную земной, и признаки жизни, но без пригодной для дыхания атмосферы. Правда это или ложь? Ответьте на этот вопрос, основываясь на мире, описанном в документе.",[Правда [в реальном мире: Ложь]],"[Правда [в реальном мире: Правда], Ложь [в реальном мире: Ложь], Ложь [в реальном мире: Правда]]",a01ae430-710d-444c-a00a-35a02f58b977,None
2,32k,"«КВАНТОВЫЙ СКАЧОК», автор: РОБЕРТ УИКС Иллюстратор: Ллевелин. «Капитан Брэндон был пионером. Он исследовал дальние уголки космоса и сообщал о том, как там обстоят дела. Так что было очень тревожно узнать, что «дальние уголки космоса» знали больше о том, что происходит дома, чем он сам». Брэндон...","3. Четырехлетнее путешествие космонавтов можно перевести в 17 лет пребывания на Земле, правда это или ложь? Ответьте на этот вопрос, основываясь на мире, описанном в документе.",[Ложь [в реальном мире: Ложь]],"[Правда [в реальном мире: Ложь], Правда [в реальном мире: Правда], Ложь [в реальном мире: Правда]]",987ed7ef-c09e-4c47-b39a-199bcdd20e2c,None

{'test': SplitInfo(name='test', num_bytes=7217269, num_examples=64, shard_lengths=None, dataset_name='libra')}

'ru_sci_passage_count'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,Параграф 1: Актуальность. Врожденная косолапость является сложной ортопедической патологией. Частота рецидивов или вторичных деформаций стоп может достигать 60 % случаев. Цель. Определение показаний к хирургической коррекции рецидивирующей врожденной косолапости с использованием аппарата Илизаро...,Сколько уникальных параграфов в тексте?,[6],[],ed725c20-6f80-4d86-9df6-5592584ea521,../origin_datasets/ru_sci_bench.parquet
1,8k,"Параграф 1: В статье проводится исследование по вопросу научной и эмпирической обоснованности правовых позиций Пленума Верховного Суда Российской Федерации и судебных прецедентов. С этой целью автором произведено сравнение данных правовых категорий с точки зрения науки и практики. Кроме того, пр...",Сколько уникальных параграфов в тексте?,[7],[],e3d9c5f4-0df3-4f7e-b5be-d35f7757e83d,../origin_datasets/ru_sci_bench.parquet
2,16k,"Параграф 1: В процессе развития рыночных отношений в имуществе субъектов хозяйствования неуклонно возрастает доля нематериальных активов. Это является следствием быстрого распространения информационных технологий, обострением конкуренции, стремления предприятий к выходу на новые рынки как отечес...",Сколько уникальных параграфов в тексте?,[14],[],a001e45e-feb6-4f39-bfe1-e6d3ea1e2572,../origin_datasets/ru_sci_bench.parquet

{'test': SplitInfo(name='test', num_bytes=110232625, num_examples=600, shard_lengths=None, dataset_name='libra')}

'ru_tpo'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,8k,"что ж, я собираюсь начать эту лекцию с того, что дам вам следующее задание, в общем, выставка, которую я хочу, чтобы вы посетили, приближается, на самом деле она уже началась, но она пробудет в галерее весь следующий месяц, что должно дать вам достаточно времени для выполнения этого задания, и и...","почему Францен ходила в торговый амбар? А. чтобы изучать человеческие формы и движения. Б. чтобы зарабатывать деньги, рисуя портреты. В. чтобы рисовать сельскохозяйственных животных на открытом воздухе. Г. чтобы встречаться с людьми, которые могли бы послужить для неё моделями",[А],"[Б, Г, В]",ccf1e402-5dc9-43e9-af46-7c273e8e8314,None
1,8k,"что ж, я собираюсь начать эту лекцию с того, что дам вам следующее задание, в общем, выставка, которую я хочу, чтобы вы посетили, приближается, на самом деле она уже началась, но она пробудет в галерее весь следующий месяц, что должно дать вам достаточно времени для выполнения этого задания, и и...","какова была цель первой лекции? А. объяснить разницу между двумя художественными стилями. Б. описать классу новую художественную галерею. В. показать классу работы художника. Г. показать, как стили художников могут меняться с течением времени",[В],"[Б, Г, А]",a67f4e38-0a86-4ad9-90ed-384f7bc3eeab,None
2,8k,"что ж, я собираюсь начать эту лекцию с того, что дам вам следующее задание, в общем, выставка, которую я хочу, чтобы вы посетили, приближается, на самом деле она уже началась, но она пробудет в галерее весь следующий месяц, что должно дать вам достаточно времени для выполнения этого задания, и и...","что профессор говорит о картине Францен, изображающей сцену на ферме? А. она напоминает фотографию. Б. возможно, это самая известная картина Францен. В. она написана в стиле импрессионизма. Г. она была написана, когда Францен жила за границей",[В],"[Б, Г, А]",5273e19e-c19a-46c3-baa4-5a5fb5556db2,None

{'test': SplitInfo(name='test', num_bytes=7921499, num_examples=251, shard_lengths=None, dataset_name='libra')}

'ru_trec'

,length,context,input,positive_outputs,negative_outputs,metadata_id,metadata_source_path
0,4k,"Вопрос: Из какой единственной страны вам разрешили въехать в Израиль в 1979 году?\nТип: Страна\nВопрос: Как звали косатку, которая умерла от грибковой инфекции?\nТип: Животное\nВопрос: Кто сыграл Фэтмена в сериале «Джейк и Толстяк»?\nТип: Личность\nВопрос: Что означает СВДС?\nТип: Выражение сокр...",Вопрос: Что такое нанотехнологии?\nТип:,[Определение чего-либо],[],d755f085-4b41-4b26-a72c-989c47fa2f84,ru_trec
1,8k,Вопрос: В каком штате США находится Диксвилл Нотч?\nТип: Состояние\nВопрос: Кто зять Арчи Банкера?\nТип: Личность\nВопрос: Сколько языков существует в мире?\nТип: Количество чего-либо\nВопрос: Что такое страх детей?\nТип: Болезни и лекарства\nВопрос: Каково происхождение слова «чердак»?\nТип: Оп...,Вопрос: В какой день и месяц умер Джон Леннон?\nТип:,[Дата],[],222c3efb-1ece-4d7f-935d-834fb8911dda,ru_trec
2,8k,"Вопрос: Почему Чикаго называют Чикаго?\nТип: Причина\nВопрос: Что такого сказал Ленни Брюс, что привело к его аресту?\nТип: Описание чего-либо\nВопрос: За какой фильм Луиза Флетчер получила премию «Оскар» за лучшую женскую роль?\nТип: Изобретение, книга, другое творческое произведение\nВопрос: К...",Вопрос: Сколько адмиралов в ВМС США?\nТип:,[Количество чего-либо],[],4dfbb3c8-07b0-405a-962d-10559053394b,ru_trec

{'test': SplitInfo(name='test', num_bytes=18657206, num_examples=300, shard_lengths=None, dataset_name='libra')}